// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_C2SOperationsNC.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.apache.cassandra.ice;

public interface _C2SOperationsNC
{
    void Get(String bucketID, String objID, ByteSeqHolder content);

    void Put(String bucketID, String objID, byte[] content);

    void Append(String bucketID, String objID, byte[] content);

    void Delete(String bucketID, String objID);

    long Size(String bucketID, String objID);

    void Process(String bucketID, String objID);
}
