// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `C2SPrxHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.apache.cassandra.ice;

public final class C2SPrxHolder
{
    public
    C2SPrxHolder()
    {
    }

    public
    C2SPrxHolder(C2SPrx value)
    {
        this.value = value;
    }

    public C2SPrx value;
}
